name: 'Increment Version'
description: 'Increments the previous semver version adhering to the given release type'
inputs:
  version:
    description: The semver version to increment.
    required: true
  release-type:
    description: The release type. One of [major, premajor, minor, preminor, patch, prepatch, prerelease]
    required: true
  prerelease-id:
    description: The prerelease identifier
    required: false

outputs:
  previous-version:
    description: The previous version
  next-version:
    description: The incremented version
  
runs:
  using: 'node16'
  main: 'release/index.js'