name: Github JavaScript Actions CI/CD

on:
  release:
    types: [published]

jobs:
  release:
    name: Create and modify tags for GitHub Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn
    - name: Release GitHub Action
      uses: technote-space/release-github-actions@v8
      with:
        CLEAN_TARGETS: Source,*.ts,*.js,*.json,*.lock,.[!.]*,Tests,Documentation,node_modules,Distribution
        TEST_TAG_PREFIX: test/
        ORIGINAL_TAG_PREFIX: original/
        CLEAN_TEST_TAG: true

